package testiJaTarkistus.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import testiJaTarkistus.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.05.21 06:35:22 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class alkoTarkastusTest {



  // Generated by ComTest BEGIN
  /** testAlkoTark19 */
  @Test
  public void testAlkoTark19() {    // alkoTarkastus: 19
    alkoTarkastus tarkastus = new alkoTarkastus(); 
    assertEquals("From: alkoTarkastus line: 21", "Ei ole numero väliltä 0-100", tarkastus.alkoTark("121212-222")); 
    assertEquals("From: alkoTarkastus line: 22", "Ei ole numero väliltä 0-100", tarkastus.alkoTark("121")); 
    assertEquals("From: alkoTarkastus line: 23", "5", tarkastus.alkoTark("5")); 
    assertEquals("From: alkoTarkastus line: 24", "Ei ole numero väliltä 0-100", tarkastus.alkoTark("gsdsdgs")); 
    assertEquals("From: alkoTarkastus line: 25", "0", tarkastus.alkoTark("0")); 
    assertEquals("From: alkoTarkastus line: 26", "100", tarkastus.alkoTark("100")); 
  } // Generated by ComTest END
}