package kanta.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kanta.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.05.21 04:41:59 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class OlutTest {



  // Generated by ComTest BEGIN
  /** testAnna106 */
  @Test
  public void testAnna106() {    // Olut: 106
    Olut koff = new Olut(); 
    koff.parse("   200 |   koff   |  5  |  20   | Suomi | 3 | Nam "); 
    assertEquals("From: Olut line: 109", "200", koff.anna(0)); 
    assertEquals("From: Olut line: 110", "koff", koff.anna(1)); 
    assertEquals("From: Olut line: 111", "5", koff.anna(2)); 
    assertEquals("From: Olut line: 112", "20", koff.anna(3)); 
    assertEquals("From: Olut line: 113", "Suomi", koff.anna(4)); 
    assertEquals("From: Olut line: 114", "3", koff.anna(5)); 
    assertEquals("From: Olut line: 115", "Nam", koff.anna(6)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAseta148 */
  @Test
  public void testAseta148() {    // Olut: 148
    Olut koff = new Olut(); 
    assertEquals("From: Olut line: 150", "Alkoholiprosentin kentässä vääriä merkkejä = \"kissa\"", koff.aseta(2,"koira")); 
    assertEquals("From: Olut line: 151", null, koff.aseta(1,"koff")); 
    assertEquals("From: Olut line: 152", null, koff.aseta(5,"5")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone205 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone205() throws CloneNotSupportedException {    // Olut: 205
    Olut koff = new Olut(); 
    koff.parse("   2   |  10  |   Kalastus  | 1949 | 22 t "); 
    Olut kopio = koff.clone(); 
    assertEquals("From: Olut line: 210", koff.toString(), kopio.toString()); 
    koff.parse("   1   |  11  |   Uinti  | 1949 | 22 t "); 
    assertEquals("From: Olut line: 212", false, kopio.toString().equals(koff.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi260 */
  @Test
  public void testRekisteroi260() {    // Olut: 260
    Olut koff = new Olut(); 
    assertEquals("From: Olut line: 262", 0, koff.getMerkkiID()); 
    koff.rekisteroi(); 
    Olut karjala = new Olut(); 
    karjala.rekisteroi(); 
    int n1 = koff.getMerkkiID(); 
    int n2 = karjala.getMerkkiID(); 
    assertEquals("From: Olut line: 268", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetMerkki281 */
  @Test
  public void testGetMerkki281() {    // Olut: 281
    Olut koff = new Olut(); 
    koff.vastaaKoff(1); 
    { String _l_=koff.getMerkki(),_r_="Koff .*"; if ( !_l_.matches(_r_) ) fail("From: Olut line: 284" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString442 */
  @Test
  public void testToString442() {    // Olut: 442
    Olut koff = new Olut(); 
    koff.parse("   5   |  koff  |  4.5  | 20 | Suomi | 3.0 | Oli nannaa "); 
    assertEquals("From: Olut line: 445", "5|koff|4.5|20|Suomi|3.0|Oli nannaa", koff.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse466 */
  @Test
  public void testParse466() {    // Olut: 466
    Olut koff = new Olut(); 
    koff.parse("   5   |  koff  |  4.5  | 20 | Suomi | 3.0 | Oli nannaa "); 
    assertEquals("From: Olut line: 469", 20, koff.getTyyppiID()); 
    assertEquals("From: Olut line: 470", "5|koff|4.5|20|Suomi|3.0|Oli nannaa", koff.toString()); 
    koff.rekisteroi(); 
    int n = koff.getMerkkiID(); 
    koff.parse(""+(n+10)); 
    koff.rekisteroi(); 
    assertEquals("From: Olut line: 476", n+10+1, koff.getMerkkiID()); 
    assertEquals("From: Olut line: 477", "" + (n+10+1) + "|koff|4.5|20|Suomi|3.0|Oli nannaa", koff.toString()); 
  } // Generated by ComTest END
}